import type { WindGridPoint } from "./types.ts";

/**
 * A regular lat/lon grid of wind flow vectors, decomposed for particle
 * advection. `u`/`v` are unit flow-direction components (not real
 * m/s->degrees physics - this is a decorative visualization, not
 * navigation, so advection speed is calibrated for a pleasant on-screen
 * animation, not physical accuracy). Row-major, matching
 * domain/windGrid.ts's buildWindGrid iteration order (i=lat outer,
 * j=lon inner), so index = row * cols + col.
 */
export interface WindFieldGrid {
  cols: number;
  rows: number;
  minLat: number;
  maxLat: number;
  minLon: number;
  maxLon: number;
  /** Eastward flow-direction unit component per cell (sin of the TOWARD bearing), NaN where no data. */
  u: Float32Array;
  /** Northward flow-direction unit component per cell (cos of the TOWARD bearing), NaN where no data. */
  v: Float32Array;
  /** Wind speed in m/s per cell, NaN where no data - drives both color and advection magnitude. */
  speedMs: Float32Array;
}

/**
 * Builds a WindFieldGrid from the raw per-point hourly grid at one
 * slider index. Assumes `points` is a complete, regular row-major NxN
 * grid (true for every value scripts/collect-forecasts.ts publishes,
 * generated by domain/windGrid.ts's buildWindGrid) - `cols`/`rows` are
 * derived from sqrt(length) rather than passed in, since the frontend
 * never knows the resolution ahead of time and re-deriving it here
 * keeps this function self-contained and testable without a second
 * source of truth for the grid shape.
 *
 * Wind direction is meteorological convention (direction wind comes
 * FROM, same as every other value in this app - §29.3) - flipped +180
 * to get the TOWARD bearing particles actually flow along, same
 * conversion WindArrow.tsx already applies for its own flow arrows.
 *
 * Returns null for an empty or non-square point list (no usable grid
 * yet, e.g. before the fetch resolves) - never fabricates a grid shape.
 */
export function buildWindFieldGrid(points: WindGridPoint[], sliderIndex: number): WindFieldGrid | null {
  if (points.length === 0) return null;
  const side = Math.round(Math.sqrt(points.length));
  if (side * side !== points.length) return null;

  const cols = side;
  const rows = side;
  const u = new Float32Array(points.length);
  const v = new Float32Array(points.length);
  const speedMs = new Float32Array(points.length);

  let minLat = Infinity;
  let maxLat = -Infinity;
  let minLon = Infinity;
  let maxLon = -Infinity;

  for (let i = 0; i < points.length; i++) {
    const p = points[i];
    minLat = Math.min(minLat, p.lat);
    maxLat = Math.max(maxLat, p.lat);
    minLon = Math.min(minLon, p.lon);
    maxLon = Math.max(maxLon, p.lon);

    const dirFrom = p.windDirectionDeg[sliderIndex];
    const speed = p.windSpeedMs[sliderIndex];
    if (dirFrom === null || dirFrom === undefined || speed === null || speed === undefined) {
      u[i] = NaN;
      v[i] = NaN;
      speedMs[i] = NaN;
      continue;
    }
    const towardRad = ((dirFrom + 180) * Math.PI) / 180;
    u[i] = Math.sin(towardRad);
    v[i] = Math.cos(towardRad);
    speedMs[i] = speed;
  }

  return { cols, rows, minLat, maxLat, minLon, maxLon, u, v, speedMs };
}

/**
 * Bilinearly samples the grid at an arbitrary lat/lon, blending the
 * surrounding 4 cells' flow direction and speed. Returns null outside
 * the grid's bounds, or if all 4 surrounding cells are NaN (no data),
 * so callers can respawn/skip a particle rather than advect it with
 * fabricated wind.
 */
export function sampleWindField(
  grid: WindFieldGrid,
  lat: number,
  lon: number,
): { u: number; v: number; speedMs: number } | null {
  if (lat < grid.minLat || lat > grid.maxLat || lon < grid.minLon || lon > grid.maxLon) return null;

  const latSpan = grid.maxLat - grid.minLat || 1;
  const lonSpan = grid.maxLon - grid.minLon || 1;
  const fy = ((lat - grid.minLat) / latSpan) * (grid.rows - 1);
  const fx = ((lon - grid.minLon) / lonSpan) * (grid.cols - 1);

  const row0 = Math.max(0, Math.min(grid.rows - 1, Math.floor(fy)));
  const row1 = Math.min(grid.rows - 1, row0 + 1);
  const col0 = Math.max(0, Math.min(grid.cols - 1, Math.floor(fx)));
  const col1 = Math.min(grid.cols - 1, col0 + 1);
  const ty = fy - row0;
  const tx = fx - col0;

  const idx = (r: number, c: number) => r * grid.cols + c;
  const corners = [idx(row0, col0), idx(row0, col1), idx(row1, col0), idx(row1, col1)];
  const weights = [(1 - ty) * (1 - tx), (1 - ty) * tx, ty * (1 - tx), ty * tx];

  let u = 0;
  let v = 0;
  let speedMs = 0;
  let weightSum = 0;
  for (let k = 0; k < 4; k++) {
    const i = corners[k];
    if (Number.isNaN(grid.u[i])) continue;
    const w = weights[k];
    u += grid.u[i] * w;
    v += grid.v[i] * w;
    speedMs += grid.speedMs[i] * w;
    weightSum += w;
  }
  if (weightSum === 0) return null;
  return { u: u / weightSum, v: v / weightSum, speedMs: speedMs / weightSum };
}

/**
 * Speed color ramp - anchor colors match WindArrowField/WindArrow.tsx's
 * own speedColor() bands exactly (calm blue through strong red), so the
 * animated particle field and the reduced-motion static arrow fallback
 * read as the same visual language, not two different color scales.
 * Exposed as anchors (not a stepped function) so the WebGL layer can
 * build a smooth gradient rather than hard color bands, which reads
 * better for continuously-flowing particles than discrete steps do.
 */
export const WIND_SPEED_COLOR_STOPS: { speedMs: number; rgb: [number, number, number] }[] = [
  { speedMs: 0, rgb: [0x90, 0xca, 0xf9] },
  { speedMs: 2, rgb: [0x42, 0xa5, 0xf5] },
  { speedMs: 5, rgb: [0x66, 0xbb, 0x6a] },
  { speedMs: 8, rgb: [0xff, 0xa7, 0x26] },
  { speedMs: 12, rgb: [0xef, 0x53, 0x50] },
];

/** Linearly interpolated RGB (0-1 range, for WebGL vertex colors) for a given speed, clamped to the ramp's endpoints. */
export function speedToColor(speedMs: number): [number, number, number] {
  const stops = WIND_SPEED_COLOR_STOPS;
  if (speedMs <= stops[0].speedMs) return normalize(stops[0].rgb);
  const last = stops[stops.length - 1];
  if (speedMs >= last.speedMs) return normalize(last.rgb);

  for (let i = 0; i < stops.length - 1; i++) {
    const a = stops[i];
    const b = stops[i + 1];
    if (speedMs >= a.speedMs && speedMs <= b.speedMs) {
      const t = (speedMs - a.speedMs) / (b.speedMs - a.speedMs);
      return [
        lerp(a.rgb[0], b.rgb[0], t) / 255,
        lerp(a.rgb[1], b.rgb[1], t) / 255,
        lerp(a.rgb[2], b.rgb[2], t) / 255,
      ];
    }
  }
  return normalize(last.rgb);
}

function lerp(a: number, b: number, t: number): number {
  return a + (b - a) * t;
}

function normalize(rgb: [number, number, number]): [number, number, number] {
  return [rgb[0] / 255, rgb[1] / 255, rgb[2] / 255];
}
