import { Popup, type Map as MapLibreGLMap, type MapMouseEvent } from "maplibre-gl";
import type { AirspaceCategory } from "../../domain/airspaceTypes.ts";

export const AIRSPACE_SOURCE_ID = "airspace-source";
export const AIRSPACE_FILL_LAYER_ID = "airspace-fill";
export const AIRSPACE_LINE_LAYER_ID = "airspace-line";

const CATEGORY_COLORS: Record<AirspaceCategory, string> = {
  hazard: "#c62828", // restricted/danger/prohibited - avoid
  controlled: "#1565c0", // CTR/TMA/FIR/etc - needs clearance, not necessarily forbidden
  sport: "#2e7d32", // gliding sectors - directly relevant to paragliding, not a hazard
  other: "#616161",
};


let popup: Popup | null = null;

function showAirspacePopup(map: MapLibreGLMap, e: MapMouseEvent) {
  const feature = map.queryRenderedFeatures(e.point, { layers: [AIRSPACE_FILL_LAYER_ID] })[0];
  if (!feature) return;
  const p = feature.properties;
  popup?.remove();
  popup = new Popup({ closeButton: true, maxWidth: "260px" })
    .setLngLat(e.lngLat)
    .setHTML(
      `<strong>${p.name}</strong><br/>${p.typeLabel} &middot; Class ${p.icaoClassLabel}<br/>${p.lowerLimitLabel} &ndash; ${p.upperLimitLabel}`,
    )
    .addTo(map);
}

/**
 * Airspace layer (Block 17) - user-toggled, off by default (unlike
 * Block 18's always-on Skyways layer): 663 polygons covering SE+DK
 * would visually compete with the wind roses that are this app's
 * primary content on first load, so it's opt-in reference info rather
 * than default clutter - matches flyxc's own default-off convention for
 * its optional overlay layers.
 *
 * Source data: public/static/airspaces.json, generated by
 * scripts/collect-airspaces.ts from OpenAIP's API on a slow (weekly)
 * cadence - see docs/DECISIONS.md for why this isn't fetched live from
 * OpenAIP directly (API key can't be exposed client-side).
 *
 * Idempotent - safe to call when the source/layers are already present.
 */
export function addAirspaceLayer(map: MapLibreGLMap, dataUrl: string): void {
  if (map.getSource(AIRSPACE_SOURCE_ID)) return;
  map.addSource(AIRSPACE_SOURCE_ID, {
    type: "geojson",
    data: dataUrl,
    attribution: '&copy; <a href="https://www.openaip.net">OpenAIP</a>',
  });
  map.addLayer({
    id: AIRSPACE_FILL_LAYER_ID,
    type: "fill",
    source: AIRSPACE_SOURCE_ID,
    paint: {
      "fill-color": [
        "match",
        ["get", "category"],
        "hazard",
        CATEGORY_COLORS.hazard,
        "controlled",
        CATEGORY_COLORS.controlled,
        "sport",
        CATEGORY_COLORS.sport,
        CATEGORY_COLORS.other,
      ],
      "fill-opacity": ["match", ["get", "category"], "hazard", 0.18, "controlled", 0.1, "sport", 0.14, 0.06],
    },
  });
  map.addLayer({
    id: AIRSPACE_LINE_LAYER_ID,
    type: "line",
    source: AIRSPACE_SOURCE_ID,
    paint: {
      "line-color": [
        "match",
        ["get", "category"],
        "hazard",
        CATEGORY_COLORS.hazard,
        "controlled",
        CATEGORY_COLORS.controlled,
        "sport",
        CATEGORY_COLORS.sport,
        CATEGORY_COLORS.other,
      ],
      "line-width": ["match", ["get", "category"], "hazard", 1.5, "controlled", 1, "sport", 1.2, 0.75],
    },
  });
  map.on("click", AIRSPACE_FILL_LAYER_ID, (e) => showAirspacePopup(map, e));
  map.on("mouseenter", AIRSPACE_FILL_LAYER_ID, () => {
    map.getCanvas().style.cursor = "pointer";
  });
  map.on("mouseleave", AIRSPACE_FILL_LAYER_ID, () => {
    map.getCanvas().style.cursor = "";
  });
}

export function removeAirspaceLayer(map: MapLibreGLMap): void {
  popup?.remove();
  popup = null;
  if (map.getLayer(AIRSPACE_LINE_LAYER_ID)) map.removeLayer(AIRSPACE_LINE_LAYER_ID);
  if (map.getLayer(AIRSPACE_FILL_LAYER_ID)) map.removeLayer(AIRSPACE_FILL_LAYER_ID);
  if (map.getSource(AIRSPACE_SOURCE_ID)) map.removeSource(AIRSPACE_SOURCE_ID);
}
